repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--config-file", "mypy.ini"]

#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.8.6
#    hooks:
#      - id: bandit
#        args: [ "-r", "src/", "--config=pyproject.toml" ]
#        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml

#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.5.0
#    hooks:
#      - id: detect-secrets
#        args: [ "--baseline", ".secrets.baseline" ]

  - repo: local
    hooks:
        - id: pytest
          name: pytest
          entry: pytest
          language: system
          pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
