services:
  postgres:
    image: postgres:17
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: users_service
      POSTGRES_PASSWORD: users_password123
      POSTGRES_DB: users_main
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "users_service", "-d", "users_main"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - users_net
  
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./alembic.ini:/app/alembic.ini:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/users/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - users_net

  redis:
    image: redis:8.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
    networks:
      - users_net
    

volumes:
  pgdata:
  redis:
    driver: local

networks:
  users_net:
    driver: bridge
  vault_net:
    external: true
