[mypy]
ignore_missing_imports = False
check_untyped_defs = True
explicit_package_bases = True

[mypy-pytest.*,sqlalchemy.*]
ignore_missing_imports = True

[mypy-jwt.*]
ignore_missing_imports = True

[mypy-pyjwt.*]
ignore_missing_imports = True

[mypy-src.infrastructure.database.migrations.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
