"""sync orm-model(user) with domain-model

Revision ID: 163adefb7724
Revises: c2b88edf3e19
Create Date: 2025-10-13 04:43:00.006456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163adefb7724'
down_revision: Union[str, Sequence[str], None] = 'c2b88edf3e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True, default=False))
    op.add_column(
        'users',
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()),
    )
    op.add_column(
        'users',
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()),
    )
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'first_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'last_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'last_name', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'first_name', existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
