"""add lock_count field in auth model

Revision ID: ae0162dc8634
Revises: 3b9037671558
Create Date: 2025-12-23 07:36:49.313152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'ae0162dc8634'
down_revision: Union[str, Sequence[str], None] = '3b9037671558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=True)
    op.add_column(
        'user_auth_state',
        sa.Column('lock_count', sa.Integer(), nullable=False, server_default=text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_state', 'lock_count')
    op.drop_index('ix_refresh_tokens_jti', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###
