"""add fields role and table user_sub

Revision ID: ecbc8e943648
Revises: 6eb2459fa1c7
Create Date: 2025-12-19 04:09:08.137541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbc8e943648'
down_revision: Union[str, Sequence[str], None] = '6eb2459fa1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum(
    'USER',
    'MODERATOR',
    'ADMIN',
    name='userrole',
)


def upgrade() -> None:
    """Upgrade schema."""

    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            user_role_enum,
            nullable=False,
            server_default='USER',  # ОБЯЗАТЕЛЬНО если NOT NULL
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
