from enum import Enum


class AuthEvent(str, Enum):
    # Создание токенов
    REFRESH_ISSUED = 'REFRESH_ISSUED'
    ACCESS_REFRESH_CREATED = 'ACCESS_REFRESH_CREATED'

    # Обновление токенов
    REFRESH_ROTATE = 'REFRESH_ROTATE'

    # Ошибки и нарушения
    REFRESH_DECODE_FAILED = 'REFRESH_DECODE_FAILED'
    REFRESH_REVOKED_ATTEMPT = 'REFRESH_REVOKED_ATTEMPT'
    REFRESH_EXPIRED = 'REFRESH_EXPIRED'
    REFRESH_FINGERPRINT_MISMATCH = 'REFRESH_FINGERPRINT_MISMATCH'
    REFRESH_MISSING = 'REFRESH_MISSING'

    # Успешный revoke
    REFRESH_REVOKE_SUCCESS = 'REFRESH_REVOKE_SUCCESS'
